version: "3.8"

services:
  app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: unless-stopped
    env_file: api.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped